import React from 'react';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { HIGHLIGHT_COLORS, getSourceNumberColor } from '@/lib/colors';
import { Source } from '@/hooks/useChatResults';


interface TextSegment {
  text: string;
  source: Source | null;
  sourceIndex: number | null;
  isAI: boolean;
}

interface SourceHighlightedTextProps {
  text: string;
  sources: Source[];
  aiRatio: number;
}

export function SourceHighlightedText({ text, sources, aiRatio }: SourceHighlightedTextProps) {
  // Creative AI formatting explanations
  const getAIExplanation = (sentence: string, index: number) => {
    const explanations = [
      {
        title: "AI-Generated Content",
        description: "This portion was generated by AI to improve readability and flow.",
        reason: "Enhanced readability",
        icon: "✨"
      },
      {
        title: "AI Transition",
        description: "AI added this transition to connect ideas more smoothly.",
        reason: "Improved flow",
        icon: "🔗"
      },
      {
        title: "AI Clarification",
        description: "AI enhanced this section to make complex concepts clearer.",
        reason: "Better clarity",
        icon: "💡"
      },
      {
        title: "AI Synthesis",
        description: "AI combined multiple source ideas into a cohesive statement.",
        reason: "Content synthesis",
        icon: "🧩"
      },
      {
        title: "AI Professional Tone",
        description: "AI adjusted the language to match professional standards.",
        reason: "Tone refinement",
        icon: "🎯"
      },
      {
        title: "AI Context Addition",
        description: "AI added contextual information to improve understanding.",
        reason: "Context enhancement",
        icon: "📚"
      },
      {
        title: "AI Structure Improvement",
        description: "AI restructured this content for better organization.",
        reason: "Structural clarity",
        icon: "🏗️"
      },
      {
        title: "AI Language Polish",
        description: "AI refined the language for more precise communication.",
        reason: "Language precision",
        icon: "✨"
      },
      {
        title: "AI Risk Mitigation",
        description: "AI added language to address potential compliance concerns.",
        reason: "Risk management",
        icon: "🛡️"
      },
      {
        title: "AI Client Focus",
        description: "AI tailored this content to be more client-friendly.",
        reason: "Client communication",
        icon: "👥"
      },
      {
        title: "AI Regulatory Alignment",
        description: "AI ensured this content meets regulatory standards.",
        reason: "Compliance alignment",
        icon: "📋"
      },
      {
        title: "AI Market Context",
        description: "AI added market-relevant context to enhance understanding.",
        reason: "Market relevance",
        icon: "📈"
      }
    ];
    
    // Use sentence characteristics to pick appropriate explanation
    const isTransition = /^(However|Furthermore|Additionally|Moreover|Therefore|Consequently|Meanwhile|Similarly)/i.test(sentence);
    const isComplex = sentence.length > 120;
    const isProfessional = /(ensure|maintain|implement|establish|facilitate|optimize)/i.test(sentence);
    const isSynthesis = /(combines|integrates|incorporates|synthesizes)/i.test(sentence);
    const isRiskRelated = /(risk|compliance|regulatory|mitigate|safeguard|protect)/i.test(sentence);
    const isClientFocused = /(client|customer|investor|stakeholder|portfolio)/i.test(sentence);
    const isMarketRelated = /(market|economic|financial|investment|performance)/i.test(sentence);
    
    if (isTransition) return explanations[1];
    if (isComplex) return explanations[2];
    if (isProfessional) return explanations[4];
    if (isSynthesis) return explanations[3];
    if (isRiskRelated) return explanations[8]; // AI Risk Mitigation
    if (isClientFocused) return explanations[9]; // AI Client Focus
    if (isMarketRelated) return explanations[11]; // AI Market Context
    
    // Default to variety based on position
    return explanations[index % explanations.length];
  };
  // Parse the text to identify AI-generated vs source content
  const parseTextWithAIHighlighting = (text: string, sources: Source[], aiRatio: number) => {
    // In a real implementation, this would come from the AI system with exact attribution
    // For now, we'll simulate this by identifying likely AI-generated portions
    
    const segments: TextSegment[] = [];
    
    // Split by sentences and analyze each
    const sentences = text.split(/(?<=[.!?])\s+/);
    let currentIndex = 0;
    
    // Track which sources have been used
    const usedSources = new Set<string>();
    const sourceUsageCount = new Map<string, number>();
    
    // Initialize source usage tracking
    sources.forEach(source => {
      sourceUsageCount.set(source.id, 0);
    });
    
    sentences.forEach((sentence, sentenceIndex) => {
      const sentenceStart = text.indexOf(sentence, currentIndex);
      const sentenceEnd = sentenceStart + sentence.length;
      
      // Determine if this sentence is likely AI-generated based on patterns
      const isAIGenerated = isLikelyAIGenerated(sentence, sentenceIndex, sentences.length, aiRatio);
      
      // Find the best matching source for this sentence
      let source = isAIGenerated ? null : findBestMatchingSource(sentence, sources);
      let sourceIndex = source ? sources.findIndex(s => s.id === source.id) : null;
      
      // If we haven't used all sources yet, try to assign unused sources
      if (!isAIGenerated && source && usedSources.has(source.id)) {
        // Try to find an unused source that could match this content
        const unusedSources = sources.filter(s => !usedSources.has(s.id));
        if (unusedSources.length > 0) {
          // Find the best unused source for this sentence
          const bestUnusedSource = findBestMatchingSource(sentence, unusedSources);
          if (bestUnusedSource) {
            source = bestUnusedSource;
            sourceIndex = sources.findIndex(s => s.id === source.id);
          }
        }
      }
      
      // If this is source content, mark it as used
      if (source) {
        usedSources.add(source.id);
        sourceUsageCount.set(source.id, (sourceUsageCount.get(source.id) || 0) + 1);
      }
      
      segments.push({
        text: sentence,
        source: source,
        sourceIndex: sourceIndex,
        isAI: isAIGenerated
      });
      
      currentIndex = sentenceEnd;
    });
    
    // Ensure all sources are represented - if any sources weren't used, 
    // convert some AI segments to source segments
    const unusedSources = sources.filter(s => !usedSources.has(s.id));
    if (unusedSources.length > 0) {
      // Find AI segments that could be converted to source segments
      const aiSegments = segments.filter((segment, index) => segment.isAI);
      const segmentsToConvert = Math.min(unusedSources.length, aiSegments.length);
      
      for (let i = 0; i < segmentsToConvert; i++) {
        const segmentIndex = segments.findIndex(seg => seg === aiSegments[i]);
        const sourceToUse = unusedSources[i];
        const sourceIndex = sources.findIndex(s => s.id === sourceToUse.id);
        
        if (segmentIndex !== -1) {
          segments[segmentIndex] = {
            ...segments[segmentIndex],
            source: sourceToUse,
            sourceIndex: sourceIndex,
            isAI: false
          };
          usedSources.add(sourceToUse.id);
        }
      }
    }
    
    return segments;
  };
  
  const isLikelyAIGenerated = (sentence: string, index: number, totalSentences: number, aiRatio: number) => {
    // Patterns that suggest AI generation
    const aiPatterns = [
      /^(This|These|Our|We|By|Through|In|With|As|To|For|Of|The|A|An)\s/, // Transition words
      /(approach|process|method|strategy|framework|system|model|tool|technique)/i, // Process words
      /(ensures|maintains|provides|delivers|focuses|emphasizes|integrates|combines)/i, // Action words
      /(disciplined|comprehensive|thorough|systematic|rigorous|consistent|effective)/i, // Descriptive words
      /(while|whereas|however|therefore|furthermore|moreover|additionally|consequently)/i, // Connectors
      /(long-term|short-term|risk-adjusted|high-quality|sustainable|competitive)/i, // Compound adjectives
    ];
    
    // Check if sentence matches AI patterns
    const matchesAIPattern = aiPatterns.some(pattern => pattern.test(sentence));
    
    // Consider position in text (AI often adds transitions at beginning/end)
    const isTransitionPosition = index === 0 || index === totalSentences - 1;
    
    // Consider sentence length (AI often creates longer, more complex sentences)
    const isLongSentence = sentence.length > 100;
    
    // Calculate probability based on AI ratio and patterns
    const aiProbability = (aiRatio / 100) * 0.7 + // Base probability from ratio
                         (matchesAIPattern ? 0.3 : 0) + // Pattern matching
                         (isTransitionPosition ? 0.2 : 0) + // Position bonus
                         (isLongSentence ? 0.1 : 0); // Length bonus
    
    return aiProbability > 0.5;
  };
  
  const findBestMatchingSource = (content: string, sources: Source[]) => {
    const contentLower = content.toLowerCase();
    
    for (const source of sources) {
      if (source.snippet.toLowerCase().includes(contentLower) || 
          contentLower.includes(source.name.toLowerCase().split('.')[0])) {
        return source;
      }
    }
    
    return sources[0] || null;
  };
  
  const textSegments = parseTextWithAIHighlighting(text, sources, aiRatio);
  
  // Calculate source coverage statistics
  const usedSources = new Set(textSegments.filter(seg => seg.source).map(seg => seg.source!.id));
  const sourceCoverage = `${usedSources.size}/${sources.length} sources used`;
  
  return (
    <span>
      {textSegments.map((segment, index) => {
        const isPreviousAISegment = index > 0 && textSegments[index - 1].isAI;
        const isNextAISegment = index < textSegments.length - 1 && textSegments[index + 1].isAI;
        
        if (segment.isAI) {
          const explanation = getAIExplanation(segment.text, index);
          return (
            <Tooltip key={index}>
              <TooltipTrigger asChild>
                <span className={`underline ${HIGHLIGHT_COLORS.ai.underline} ${HIGHLIGHT_COLORS.ai.underlineHover} decoration-[1.5px] cursor-help mr-2 transition-colors leading-6 ${
                  isPreviousAISegment ? 'ml-0.5' : ''
                } ${isNextAISegment ? 'mr-0.5' : ''}`}>{segment.text}</span>
              </TooltipTrigger>
              <TooltipContent side="top" className="max-w-xs">
                <div className="space-y-2">
                  <div className={`font-medium text-sm ${HIGHLIGHT_COLORS.ai.text} flex items-center gap-1`}>
                    {explanation.title}
                  </div>
                  <div className="text-xs text-gray-600">
                    {explanation.description}
                  </div>
                  <div className="flex items-center gap-2 text-xs">
                    <span className={`${HIGHLIGHT_COLORS.ai.accent} font-medium`}>AI Enhancement</span>
                    <span className="text-gray-400">•</span>
                    <span className="text-gray-500">{explanation.reason}</span>
                  </div>
                </div>
              </TooltipContent>
            </Tooltip>
          );
        }
        
        // Vault source content - show with blue underline and hover tooltip
        if (segment.source && segment.sourceIndex !== null) {
          return (
            <Tooltip key={index}>
              <TooltipTrigger asChild>
                <span>
                  <span className={`underline ${HIGHLIGHT_COLORS.vault.underline} decoration-[1.5px] decoration-dotted hover:decoration-solid mr-1 leading-6 cursor-help ${HIGHLIGHT_COLORS.vault.underlineHover} transition-colors`}>{segment.text}</span>
                  <span className={`inline-flex items-center justify-center w-4 h-4 mr-2 text-xs font-bold text-white rounded-sm ${getSourceNumberColor(segment.sourceIndex)}`}>
                    {segment.sourceIndex + 1}
                  </span>
                </span>
              </TooltipTrigger>
              <TooltipContent side="top" className="max-w-xs">
                <div className="space-y-2">
                  <div className={`font-medium text-sm ${HIGHLIGHT_COLORS.vault.text}`}>Vault Source #{segment.sourceIndex + 1}</div>
                  <div className="text-xs text-gray-600">
                    Content from: <span className="font-medium">{segment.source.name}</span>
                  </div>
                  <div className="flex items-center gap-2 text-xs">
                    <span className={`${HIGHLIGHT_COLORS.vault.accent} font-medium`}>{segment.source.similarity}% match</span>
                    <span className="text-gray-400">•</span>
                    <span className="text-gray-500">Firm-approved language</span>
                  </div>
                  {segment.source.strategy && (
                    <div className="text-xs text-gray-500">
                      Strategy: {segment.source.strategy}
                    </div>
                  )}
                </div>
              </TooltipContent>
            </Tooltip>
          );
        }
        
        return <span key={index}>{segment.text}</span>;
      })}
    </span>
  );
}
