import { ContentItem } from "@/types/vault";

// Generate realistic demo data with hierarchical structure
export const MOCK_CONTENT_ITEMS: ContentItem[] = [
  {
    id: "1",
    title: "AI_Policy_Document_April_2025",
    items: [
      {
        id: "1-1",
        type: "Policies",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["AI", "Policy", "Compliance"],
        question: "What specific pre-approval requirements must Granite Peak employees adhere to when using AI Systems involving proprietary information, and what roles do the Deputy CCO and Director of Operations play in the due diligence process to prevent unauthorized sharing of confidential information?",
        answer: "Granite Peak maintains an Acceptable Use of Artificial Intelligence (\"AI\") Systems Policy (below). The use of artificial intelligence and natural language processing programs and related software i.e., ChatGPT, CoPilot, Bard, and others by the Firm and its employees must comply with all applicable laws, regulations, and the ethical principles outlined in this Compliance Manual and the Firm's Code of Ethics, including those related to the protection of sensitive firm and client information outlined in the Firm's Cybersecurity and Information Security Policy. Before formally implementing any such software, employees must first obtain approval from the Deputy Chief Compliance Officer and Director of Operations. At this time, use of this software is limited to testing only and may not be used for any client facing business purposes i.e., generating investment advice, producing client reports, etc. The Firm and its employees shall comply with the Firm's data protection measures to safeguard sensitive firm and client information when using such software. This includes continued use of firewalls, encryption, access controls, and other measures as outlined in the Firm's Cybersecurity and Information Security Policy and as deemed necessary by Compliance. At this time, inputting client data into any unsupported AI system is prohibited. Supported AI systems include Firm approved vendors who have their own proprietary AI system within their platform). Should the parameters surround inputting client data change, the Firm shall provide appropriate disclosures to clients regarding the use of such software in formulating investment advice, reports, etc. to the extent deemed necessary. The Firm shall implement appropriate risk management measures to mitigate potential risks associated with the use of AI systems and related software, including disaster recovery planning and regular system backups. The use of such software will be subject to ongoing supervision and monitoring by Compliance. This includes conducting regular reviews of output generated by the software, as well as monitoring data feeds and other inputs. Employees will receive appropriate training on the proper use of these tools, including data protection, model validation, and ethical considerations.",
        updatedAt: "2025-08-27T10:00:00Z",
        updatedBy: "Brian Stone",
        isBestAnswer: true
      }
    ]
  },
  {
    id: "2",
    title: "Artificial Intelligence (AI) Policy",
    items: [
      {
        id: "2-1",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Client Engagement", "Operational Efficiency", "Risk Assessment", "Regulatory Compliance"],
        question: "What guidelines should be followed to ensure data accuracy in AI-driven processes for client and regulatory disclosures? How should client inquiries be handled when using AI systems, according to best practices in client engagement?",
        answer: "3.3 Operational Efficiency AI-powered systems can streamline back-office processes such as client reporting, fraud detection, and regulatory reporting. - Guideline: Implement robust controls to validate AI-driven processes and ensure data accuracy before client or regulatory disclosures. 3.4 Client Engagement Chatbots and natural language processing tools can be used for routine inquiries, client onboarding, and personalized insights. - Guideline: Implement clear disclaimers to inform clients that they are interacting with an AI system. Escalate complex inquiries to qualified personnel when necessary. 3.5 Risk Assessment AI can support risk management by scanning for anomalies in trading patterns, market movements, or operational data. - Guideline: Periodically review the accuracy and fairness of AI-driven risk scores, ensuring they do not unintentionally discriminate against any group or client segment.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Sarah Chen"
      },
      {
        id: "2-2",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Data Management", "Risk Management", "Compliance", "Ethical AI", "AI Governance", "Asset Management"],
        question: "What is the role of the AI Governance Committee in ensuring compliance with policy and regulatory requirements for high-impact AI initiatives in asset management activities?",
        answer: "2.2 AI Governance Committee - Policy Maintenance: Oversee the development, review, and enforcement of the AI Policy. - Project Review: Evaluate high-impact AI initiatives for compliance with policy and regulatory requirements. - Ethical Considerations: Monitor ethical implications of AI implementations, ensuring fairness, transparency, and accountability. 2.3 IT and Data Management Teams - Infrastructure: Provide and maintain secure infrastructure for AI development and deployment. - Data Quality: Oversee data collection, storage, cleansing, and governance to ensure data integrity and security for AI models. - Compliance: Enforce data protection regulations and ensure data processing aligns with relevant laws. 2.4 Business Units and End Users - Compliance: Adhere to the AI Policy when using AI tools in daily operations, especially for asset management activities. - Risk Identification: Report potential risks, errors, or biases found in AI outputs or usage. - Training: Complete mandatory AI training to understand responsibilities and guidelines.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Michael Rodriguez"
      },
      {
        id: "2-3",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Business Continuity", "Asset Management"],
        question: "What measures should be in place to ensure business continuity in asset management services in the event of AI-related issues?",
        answer: "5.4 Contingency and Backup Plans - Fallback Mechanisms: Maintain human-driven processes or simpler analytical models that can take over in case of AI failure or unavailability. - Business Continuity: Ensure robust backup plans so critical asset management services are not interrupted due to AI-related issues. 6. Training and Awareness 6.1 Mandatory Training - Policy Training: All employees and contractors must complete training on this AI Policy and any subsequent updates. - Technical Training: Specialized training programs should be provided to data scientists, machine learning engineers, and other technical staff on best practices for model development and deployment. - Ethical & Compliance Training: Emphasize the importance of fairness, transparency, and legal compliance when using AI.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Jennifer Liu"
      },
      {
        id: "2-4",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Business Continuity", "Ethical AI", "Asset Management"],
        question: "What mechanisms should be in place for asset management services to continue uninterrupted in case of AI failure or unavailability?",
        answer: "5.4 Contingency and Backup Plans - Fallback Mechanisms: Maintain human-driven processes or simpler analytical models that can take over in case of AI failure or unavailability. - Business Continuity: Ensure robust backup plans so critical asset management services are not interrupted due to AI-related issues. 6. Training and Awareness 6.1 Mandatory Training - Policy Training: All employees and contractors must complete training on this AI Policy and any subsequent updates. - Technical Training: Specialized training programs should be provided to data scientists, machine learning engineers, and other technical staff on best practices for model development and deployment. - Ethical & Compliance Training: Emphasize the importance of fairness, transparency, and legal compliance when using AI.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "David Thompson"
      },
      {
        id: "2-5",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Intellectual Property", "Risk Management", "Governance"],
        question: "What measures should be taken to protect AI innovations through patents and trademarks according to the IP Management section of the text?",
        answer: "8. Intellectual Property (IP) Management 8.1 Ownership - In-House Development: AI solutions developed internally or by employees on company time or with company resources are the exclusive property of [Your Organization Name]. - Collaborative Development: Joint AI initiatives must have clearly defined ownership and licensing terms agreed upon during project inception. 8.2 Protection of IP - Patents and Trademarks: Where applicable, seek patent or trademark protection for AI innovations. - Confidentiality: Implement non-disclosure agreements (NDAs) and strict access controls to protect proprietary models, methodologies, and data. 9. Auditing and Reporting 9.1 Internal Audits - Scope: Internal audits will regularly evaluate AI policies, controls, risk management processes, and compliance with regulatory requirements. - Reporting: Audit findings should be reported to the AI Governance Committee and Senior Management with recommended actions.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Amanda Foster"
      },
      {
        id: "2-6",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Risk Management", "Regulatory Compliance", "Transparency", "Financial Regulations", "Client Communication", "Asset Management"],
        question: "What steps should asset management professionals take to ensure AI model interpretability and maintain clear documentation on model assumptions and limitations?",
        answer: "4.3 Explainability and Transparency - Model Interpretability: Opt for AI methods that offer a reasonable degree of interpretability, especially in client-facing or high-stakes decision-making contexts. - Documentation: Maintain clear documentation on model assumptions, design, and limitations for internal reference and external audits. 4.4 Regulatory Compliance - Financial Regulations: Ensure AI tools comply with asset management regulations, such as those from the SEC, FINRA, FCA, or local regulatory bodies. - Reporting: Disclose material AI usage in financial statements or regulatory filings if it significantly affects asset management processes or client outcomes. - Third-Party Services: Conduct thorough vendor due diligence for third-party AI solutions to ensure they meet organizational and regulatory standards. 5. Risk Management and Monitoring",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Robert Kim"
      },
      {
        id: "2-7",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["AI Ethics", "Data Protection", "Asset Management"],
        question: "What measures are recommended to ensure compliance with data protection regulations such as GDPR and CCPA in AI training and inference processes? How can asset management professionals minimize biases in AI models to ensure fairness and integrity, especially concerning protected characteristics like gender, race, and ethnicity?",
        answer: "4. Ethical and Compliance Considerations 4.1 Data Privacy and Protection - Regulatory Compliance: All data used for AI training and inference must comply with applicable data protection regulations such as GDPR, CCPA, or equivalent local laws. - Access Controls: Employ strict access controls and encryption measures to protect sensitive client and organizational data. - Consent and Transparency: Obtain necessary consents for data collection and usage. Clients and employees must be informed about how their data will be used in AI systems. 4.2 Bias and Fairness - Data Sampling: Use representative datasets to minimize biases in AI models. - Model Validation: Continuously test models for potential discrimination or skewed outputs based on protected characteristics (e.g., gender, race, ethnicity). - Remediation: If any biases or unfair patterns are detected, take immediate action to retrain or adjust models to maintain fairness and integrity.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Lisa Wang"
      },
      {
        id: "2-8",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["AI Initiatives", "Risk Assessment", "Operational Risk", "Asset Management"],
        question: "What factors should be considered in the formal risk assessment process for AI initiatives in asset management, including evaluating operational, compliance, and reputational risks? What steps are involved in model lifecycle management for AI initiatives in asset management, from development and validation to deployment and monitoring?",
        answer: "5.1 Risk Assessment All AI initiatives must undergo a formal risk assessment process that includes: - Operational Risk: Evaluate dependencies on third-party data, software reliability, and process disruption potential. - Compliance Risk: Assess legal and regulatory implications related to AI usage in asset management. - Reputational Risk: Consider the potential impact on the organization's brand if AI tools fail or produce unethical outcomes. 5.2 Model Lifecycle Management - Development: Follow standardized processes for data collection, feature engineering, and model training. - Validation: Conduct rigorous testing, including cross-validation and out-of-sample testing. - Deployment: Implement pilot programs or controlled releases before full deployment. - Monitoring: Continuously monitor model performance metrics, data drift, and potential anomalies. 5.3 Incident Response - Detection: Establish automated alerts for model underperformance or anomalies. - Escalation: Define clear roles and responsibilities for incident response teams. - Remediation: Execute prompt corrective actions, including rolling back to a previous model version or updating input data. - Post-Mortem: Conduct root-cause analysis to improve processes and prevent recurrence.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Christopher Lee"
      },
      {
        id: "2-9",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["AI Ethics", "Risk Assessment", "Regulatory Compliance", "Asset Management"],
        question: "What are the procedures for engaging third-party experts for AI ethics and bias audits in asset management processes?",
        answer: "9.2 External Audits and Assessments - Regulatory Audits: Cooperate fully with regulatory bodies during reviews of AI-driven asset management processes. - Independent Assessments: Engage third-party experts for periodic AI ethics and bias audits, ensuring models align with best practices. 10. Policy Maintenance and Review 10.1 Policy Updates This AI Policy should be reviewed annually or when significant changes occur in technology, regulations, or organizational strategy. Revisions must be approved by the AI Governance Committee and Senior Management. 10.2 Version Control Maintain a version control system to track changes to this policy, including effective dates and reasons for updates. 10.3 Exceptions Any exceptions to this policy require written approval from the AI Governance Committee, including a formal risk assessment. ---- [Signature Block / Date] Approved By: _______________________________________ Date of Approval: ____________________________________ Next Review Date: ____________________________________ ---- End of AI Policy Document",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Maria Garcia"
      },
      {
        id: "2-10",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Data Protection", "Intellectual Property", "Ethical AI"],
        question: "What criteria should asset management professionals use to assess potential AI vendors for compliance with data protection laws and ethical AI standards? How can they ensure contractual protections regarding data usage rights and intellectual property ownership with these vendors?",
        answer: "6.2 Continuous Learning - External Engagement: Encourage AI-related seminars, certifications, and conferences to keep employees updated on emerging technologies and compliance expectations. - Internal Sharing: Foster a knowledge-sharing culture through workshops, \"lunch and learn\" sessions, and communities of practice focusing on AI. 7. Vendor Management 7.1 Vendor Selection - Due Diligence: Assess potential AI vendors on their compliance with data protection laws, security practices, and ethical AI standards. - Contractual Protections: Include provisions in vendor contracts that outline data usage rights, intellectual property ownership, and compliance obligations. 7.2 Ongoing Oversight - Performance Monitoring: Regularly evaluate vendor solutions for model accuracy, reliability, and regulatory compliance. - Security Assessments: Conduct periodic cybersecurity audits and penetration tests in collaboration with vendors to ensure data protection. - Exit Strategy: Define clear procedures for discontinuing vendor partnerships, including secure data transfer and model ownership rights.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "James Wilson"
      },
      {
        id: "2-11",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Data Analysis", "Machine Learning", "Risk Assessment", "Portfolio Management", "Asset Management"],
        question: "What guidelines should portfolio managers follow to validate AI-generated insights in client portfolio optimization within asset management? How can AI-driven machine learning models assist in market forecasting and research in asset management, and what specific guidelines should be followed to ensure accuracy and transparency in predictive estimates?",
        answer: "2.5 Risk and Compliance Teams - Oversight: Conduct periodic risk assessments of AI tools and processes. - Regulatory Monitoring: Monitor relevant regulations and advise on necessary policy updates. - Audit Support: Facilitate internal and external audits related to AI compliance and governance. 3. AI Use Cases in Asset Management 3.1 Client Portfolio Optimization AI-driven algorithms can help portfolio managers optimize asset allocation, rebalance portfolios, and conduct risk assessments. - Guideline: Portfolio managers must validate AI-generated insights before making final decisions to ensure no undue reliance on AI outputs. 3.2 Market Forecasting and Research Machine learning models can analyze large datasets (e.g., market data, financial news) to offer predictive insights. - Guideline: Any forecasts generated by AI must be clearly labeled as predictive estimates and supplemented by human judgment.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Patricia Brown"
      },
      {
        id: "2-12",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["AI Initiatives", "Risk Assessment", "Operational Risk", "Asset Management"],
        question: "What are the key factors that should be evaluated in the risk assessment process for AI initiatives in asset management, including operational, compliance, and reputational risks? What are the stages involved in model lifecycle management for AI in asset management, from development to monitoring, and what are the specific steps recommended for each stage?",
        answer: "5.1 Risk Assessment All AI initiatives must undergo a formal risk assessment process that includes: - Operational Risk: Evaluate dependencies on third-party data, software reliability, and process disruption potential. - Compliance Risk: Assess legal and regulatory implications related to AI usage in asset management. - Reputational Risk: Consider the potential impact on the organization's brand if AI tools fail or produce unethical outcomes. 5.2 Model Lifecycle Management - Development: Follow standardized processes for data collection, feature engineering, and model training. - Validation: Conduct rigorous testing, including cross-validation and out-of-sample testing. - Deployment: Implement pilot programs or controlled releases before full deployment. - Monitoring: Continuously monitor model performance metrics, data drift, and potential anomalies. 5.3 Incident Response - Detection: Establish automated alerts for model underperformance or anomalies. - Escalation: Define clear roles and responsibilities for incident response teams. - Remediation: Execute prompt corrective actions, including rolling back to a previous model version or updating input data. - Post-Mortem: Conduct root-cause analysis to improve processes and prevent recurrence.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Daniel Martinez"
      },
      {
        id: "2-13",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Data Management", "Risk Management", "Machine Learning", "Governance", "Senior Management", "Asset Management"],
        question: "What is the main responsibility of senior management and the board of directors in overseeing AI initiatives within asset management, including alignment with strategic objectives and risk appetite?",
        answer: "1.3 Definitions - AI (Artificial Intelligence): Algorithms and systems capable of performing tasks that typically require human intelligence, including (but not limited to) machine learning, natural language processing, and predictive analytics. - Machine Learning: A subset of AI involving computer algorithms that learn from data to make predictions or decisions without being explicitly programmed. - Data: All forms of information—structured or unstructured—collected, stored, processed, or used within the organization to develop and run AI systems. - Asset Management: The business function focused on managing client assets and investments, including activities such as portfolio management, research, strategy, and client reporting. 2. Roles and Responsibilities 2.1 Senior Management and Board of Directors - Oversight: Ensure effective governance and oversight of AI initiatives, including alignment with the organization's strategic objectives and risk appetite. - Approval: Review and approve AI-related policies, risk assessments, and significant AI deployments. - Accountability: Remain accountable for the integration of AI into critical processes while fostering a responsible AI culture.",
        updatedAt: "2025-01-21T00:00:00Z",
        updatedBy: "Rachel Taylor"
      }
    ]
  },
  {
    id: "3",
    title: "Global Emerging Markets Dunk Fund: Request for Proposal (RFP)",
    items: [
      {
        id: "3-1",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Social Responsibility", "Corporate Governance"],
        question: "How does the fund engage with companies to improve ESG practices?",
        answer: "The fund actively engages with portfolio companies, advocating for better governance practices and environmental commitments. For example, it recently worked with an infrastructure firm in India to adopt sustainable building materials.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Kevin Anderson"
      },
      {
        id: "3-2",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Industry Trends", "Investment Strategy", "Financial Metrics"],
        question: "How are companies selected for the portfolio?",
        answer: "Companies are chosen based on a combination of macroeconomic analysis, industry trends, and individual financial metrics, such as revenue growth, return on equity (ROE), and market share within their respective sectors.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Nicole White"
      },
      {
        id: "3-3",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Latin America", "Fund Management", "Emerging Markets"],
        question: "What is the geographic allocation of the fund?",
        answer: "Asia leads the allocation due to its dynamic economies, including China, India, and Southeast Asia, which offer significant growth opportunities. Latin America and Eastern Europe provide diversification and exposure to resource-rich markets.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Steven Clark"
      },
      {
        id: "3-4",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Risk Management", "Diversification", "Investment Strategy", "Corporate Governance"],
        question: "How does the fund manage political risk?",
        answer: "Political risk is managed by avoiding overconcentration in politically unstable regions and prioritizing investments in multinational companies with limited reliance on local governments.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Michelle Davis"
      },
      {
        id: "3-5",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Financial Analysis", "Investment Performance", "Emerging Markets"],
        question: "What is the historical performance of the Global Emerging Markets Dunk Fund?",
        answer: "The fund has consistently outperformed the MSCI Emerging Markets Index, leveraging strategic allocations to high-growth sectors and regions while actively managing currency risks.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Andrew Miller"
      },
      {
        id: "3-6",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Portfolio Strategy", "Financial Analysis", "Investment Strategy", "Equity Investments", "Fund Management"],
        question: "What is the typical number of holdings?",
        answer: "The fund holds 60-90 stocks, balancing diversification across regions and industries with high-conviction investments in market leaders.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Jessica Turner"
      },
      {
        id: "3-7",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Risk Management", "Market Analysis", "Emerging Markets"],
        question: "Why focus on emerging markets?",
        answer: "Emerging markets offer unique opportunities for outsized returns due to their faster economic growth, expanding middle class, and underpenetrated industries. Additionally, these regions provide diversification benefits by reducing reliance on developed market performance.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Ryan Phillips"
      },
      {
        id: "3-8",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Portfolio Strategy", "Risk Management", "Financial Planning", "Fund Management"],
        question: "What role does liquidity management play in the fund?",
        answer: "Liquidity management ensures the portfolio can adapt to market conditions. The fund avoids thinly traded stocks and maintains a cash allocation of 5-8% for flexibility.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Lauren Scott"
      },
      {
        id: "3-9",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Risk Management", "Emerging Markets"],
        question: "How does the fund navigate the challenges of emerging markets?",
        answer: "The fund leverages local expertise, robust due diligence processes, and diversified portfolios to manage risks like political instability and currency volatility. For instance, investments in export-driven companies help offset domestic economic risks.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Brandon Green"
      },
      {
        id: "3-10",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Social Impact", "Corporate Responsibility", "Sustainable Investing", "Emerging Markets"],
        question: "How does the fund incorporate ESG factors into emerging markets investing?",
        answer: "ESG considerations are critical in emerging markets, where regulatory standards often lag behind developed markets. The fund prioritizes companies actively improving their ESG practices, such as reducing carbon emissions or enhancing supply chain transparency.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Ashley Hall"
      },
      {
        id: "3-11",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Risk Management"],
        question: "How does the fund address currency volatility?",
        answer: "Currency volatility is managed through: - Investments in companies with revenue streams in stronger currencies (e.g., USD). - Use of forward contracts and other hedging instruments.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Tyler Young"
      },
      {
        id: "3-12",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Risk Management", "Portfolio Construction", "Diversification"],
        question: "What role does currency risk play in portfolio construction?",
        answer: "Currency risk is actively managed through hedging strategies and diversification across multiple currencies. For instance, investments in exporters help offset risks associated with local currency depreciation.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Samantha King"
      },
      {
        id: "3-13",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Technology"],
        question: "What industries are prioritized in the fund?",
        answer: "The fund focuses on high-growth industries such as: - Technology: Cloud computing, mobile payments, and AI development. - Consumer Goods: Companies catering to the rising middle class. - Infrastructure: Firms involved in large-scale urbanization projects.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Nathan Wright"
      },
      {
        id: "3-14",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Portfolio Management", "Investment Strategy", "Asset Management", "Financial Growth", "Fund Management", "Emerging Markets"],
        question: "What are the long-term return expectations for the fund?",
        answer: "The fund targets an average annual return of 10-14%, supported by the structural growth dynamics of emerging markets and active portfolio management.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Victoria Adams"
      },
      {
        id: "3-15",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Renewable Energy", "Latin America"],
        question: "What are examples of ESG-focused investments in the fund?",
        answer: "- A renewable energy company in Latin America that has expanded access to clean energy in rural areas. - A fintech firm in Southeast Asia that promotes financial inclusion by offering low-cost digital banking solutions.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Justin Baker"
      },
      {
        id: "3-16",
        type: "Questionnaires",
        strategy: "Global Emerging Markets",
        tags: ["Sector Allocation", "Technology Sector", "Active Management", "Investment Strategy", "Fund Performance", "Emerging Markets"],
        question: "What factors contribute to the fund's outperformance?",
        answer: "- Local Expertise: Partnerships with analysts based in emerging markets provide insights into unique growth opportunities. - Sector Allocation: Emphasis on technology and consumer goods, which are driving structural growth in emerging markets. - Active Management: Timely adjustments to regional allocations and exposure to high-conviction ideas.",
        updatedAt: "2024-12-03T00:00:00Z",
        updatedBy: "Megan Carter"
      }
    ]
  },
  {
    id: "4",
    title: "Vangaurd Demo - Alley Oop",
    items: [
      {
        id: "4-1",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Active Management"],
        question: "Who is responsible for setting the long-term strategy of the firm? Please list key individuals and committees and how those decisions are made.",
        answer: "At Oakland Investment Management, the responsibility for shaping the firm's long-term strategy rests with its senior leadership team. Strategic planning is a collaborative process, with major initiatives and direction reviewed and approved by the Oakland Management Committee. This committee brings together leaders from across the organization to ensure a comprehensive approach to decision-making. The current members of the Management Committee include: - Michael Carter, CFA, Chief Executive Officer & Chief Investment Officer - Emily Tran, CFA, Managing Director, Head of Research - David Lin, CFA, Principal, Portfolio Manager - Rachel Kim, Chief Operating Officer - Thomas Bennett, Director of Business Development - Priya Shah, General Counsel - Laura Evans, Director of Client Relations The committee meets regularly to discuss and evaluate strategic priorities, with decisions made through consensus and guided by the firm's mission and long-term objectives.",
        updatedAt: "2025-06-16T00:00:00Z",
        updatedBy: "Alexandra Moore"
      },
      {
        id: "4-2",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: [],
        question: "Please provide a brief description of the organization, including history, leadership, AUM across asset and client types, office location(s), and organizational structure.",
        answer: "Firm Overview Oakland Investment Management (\"Oakland\") is an independent, employee-owned asset management firm specializing in global and domestic equity and fixed income strategies. Since our inception in 2003, we have maintained a singular focus: delivering consistent, risk-adjusted returns for a diverse client base through disciplined, research-driven investing. Our investment philosophy is rooted in fundamental analysis and a long-term perspective. We seek to identify high-quality businesses trading at attractive valuations, leveraging deep sector expertise and a collaborative team environment. By maintaining a concentrated portfolio approach and rigorous risk controls, we aim to generate superior outcomes for our clients across market cycles. History Oakland was founded in the early 2000s by a group of seasoned investment professionals who recognized the need for a client-centric, research-intensive asset manager. The firm's founders brought together decades of experience from leading global financial institutions, united by a shared commitment to integrity, transparency, and partnership with clients. Over the past two decades, Oakland has grown steadily, expanding its investment capabilities and client relationships while remaining true to its founding principles. Our measured growth has allowed us to retain a boutique culture, prioritize client service, and attract talented professionals who share our values. Leadership Oakland's leadership team is comprised of experienced investors and business leaders. The firm is led by CEO and Chief Investment Officer, Sarah Kim, who has been with Oakland since its founding and oversees all investment activities. The executive team includes Chief Operating Officer Michael Tran, Head of Research Priya Desai, and Chief Compliance Officer David Lin. Together, they guide the firm's strategic direction and foster a collaborative, performance-oriented culture. Assets Under Management As of December 31, 2024, Oakland manages approximately $18 billion in assets across a range of strategies and client segments, including: - Institutional clients (public and corporate pension plans, endowments, and foundations) - Intermediaries (sub-advisory and model portfolios) - High-net-worth individuals and family offices Our asset mix is diversified across global equities, U.S. equities, and core fixed income strategies. Locations United States (Headquarters): Oakland's primary office is located in San Francisco, California, housing portfolio management, research, trading, client relations, compliance, and operations. United Kingdom: Oakland Investment Management (UK) Ltd, based in London, serves as a hub for research and client service for our European clients. Asia-Pacific: A representative office in Singapore extends our research reach and supports client engagement in the Asia-Pacific region. Organizational Structure Oakland operates with a flat organizational structure designed to encourage open communication and efficient decision-making. The investment team works closely with client service, operations, and compliance, ensuring alignment across all functions. The majority of the firm's partners are active in day-to-day investment and client activities, reinforcing our commitment to accountability and long-term partnership with clients. As of February 28, 2025, Oakland employs 52 professionals, including 14 partners, across its global offices.",
        updatedAt: "2025-06-16T00:00:00Z",
        updatedBy: "Benjamin Harris"
      }
    ]
  },
  {
    id: "5",
    title: "test docs",
    items: [
      {
        id: "5-1",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: [],
        question: "For each of the last five years, provide the following information regarding the firm's number of investment professionals. Provide the roles of these individuals as well.",
        answer: "Investment professionals data for the last five years:",
        table: {
          headers: ["Year Ending June 30", "Investment Professional Additions", "Investment Professional Departures", "Total Investment Professionals", "Roles of Investment Professionals"],
          rows: [
            ["2023", "5", "2", "26", "Portfolio Managers, Analysts, Researchers"],
            ["2022", "3", "1", "23", "Portfolio Managers, Analysts"],
            ["2021", "4", "3", "21", "Portfolio Managers, Analysts"],
            ["2020", "2", "2", "20", "Portfolio Managers, Analysts"],
            ["2019", "3", "1", "20", "Portfolio Managers, Analysts"]
          ]
        },
        updatedAt: "2025-04-16T00:00:00Z",
        updatedBy: "Olivia Jackson"
      },
      {
        id: "5-2",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: [],
        question: "List your firm's name, address, and year founded, as well as the name, title, telephone, email address and fax numbers for the individual(s) responsible for new business contacts.",
        answer: "Corr Investment Managers, legally incorporated in the state of New York, operates as an independently owned firm under the leadership of Brendan Corr, our CEO and founder. Address: New York, USA. Since its inception in 2000, Corr Investment Managers has been committed to providing innovative and client-focused investment solutions. Contact(s)/Title: Brendan Corr, CEO/Coolest Person. Telephone: 4157860570. Email address: Bmcorr@comcast.net. [INSERT FAX NUMBER]",
        updatedAt: "2025-04-16T00:00:00Z",
        updatedBy: "Ethan Lewis"
      }
    ]
  },
  {
    id: "6",
    title: "Comprehensive Request for Proposal (RFP)",
    items: [
      {
        id: "6-1",
        type: "Questionnaires",
        strategy: "S2 Strategy General",
        tags: ["Portfolio Management", "Financial Metrics"],
        question: "What tools are available for clients to track performance?",
        answer: "Clients have access to an interactive dashboard that provides real-time portfolio updates, performance metrics, and historical data. The portal also includes educational resources, such as market insights and strategy updates, to keep clients informed.",
        updatedAt: "2025-03-19T00:00:00Z",
        updatedBy: "Isabella Allen"
      },
      {
        id: "6-2",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Risk Management", "Compliance", "Portfolio Management", "Financial Services", "Asset Management", "Client Services"],
        question: "What is the firm's current size and structure?",
        answer: "Alley-Oop Asset Management has grown to manage over $12 billion in assets under management (AUM). The firm is structured into five core departments: Portfolio Management, Research & Analysis, Risk Management, Client Services, and Compliance, with 7 employees across its San Francisco headquarters and regional offices in New York and Chicago.",
        updatedAt: "2025-03-13T00:00:00Z",
        updatedBy: "Lucas Young"
      }
    ]
  },
  {
    id: "7",
    title: "Firm Information",
    items: [
      {
        id: "7-1",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Operational Efficiency", "Financial Services", "Leadership", "Sustainable Investing", "Wealth Management"],
        question: "Who are the key members of your team, and what are their professional backgrounds and qualifications?",
        answer: "Corr Investment Managers has a dedicated team of 7 professionals, led by Brendan Corr, who personally oversees all strategic directions for the firm. Key team members include: Brendan Corr – CEO and Founder, with 25 years of experience in investment management. Brendan's focus on forward-thinking investment strategies and client-centered service has shaped the firm's approach since its inception. Mo Cash, CFA – Chief Investment Officer, with a strong background in equity portfolio management and sustainable investing. Max Mulah, CFP® – Director of Wealth Management, responsible for client relationship management and strategic financial planning. Tom Foolery, CPA – Head of Operations, overseeing account administration, compliance, and operational efficiency. Dr. Shaq – Head of Research, specializing in macroeconomic analysis and asset allocation strategy with over a decade of experience. With Brendan Corr's leadership and our experienced team, Corr Investment Managers provides comprehensive and customized investment solutions backed by rigorous research and an unwavering commitment to client success.",
        updatedAt: "2025-03-13T00:00:00Z",
        updatedBy: "Ava King"
      },
      {
        id: "7-2",
        type: "Questionnaires",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Financial Services", "Tailored Strategies", "Industry Trends", "Finance Expertise", "Independent Firm", "Quantitative Analysis", "Investment Management", "Client Solutions", "New York", "Brendan Corr"],
        question: "Provide the firm's legal name and the state in which it is incorporated.",
        answer: "Corr Investment Managers, legally incorporated in the state of New York, operates as an independently owned firm under the leadership of Brendan Corr, our CEO and founder. Since its inception in 2000, Corr Investment Managers has been committed to providing innovative and client-focused investment solutions. Our independence allows us to remain agile and responsive to the unique needs of our clients, ensuring that we deliver tailored strategies that address their specific challenges and objectives. With a team of 7 seasoned professionals, we leverage our deep expertise in finance, economics, and quantitative analysis to maximize returns and drive exceptional results. Our New York incorporation reflects our strategic positioning in one of the world's leading financial hubs, enabling us to stay at the forefront of industry trends and opportunities.",
        updatedAt: "2025-03-13T00:00:00Z",
        updatedBy: "William Wright"
      }
    ]
  },
  {
    id: "8",
    title: "Market Data Analysis Files",
    items: [
      {
        id: "8-1",
        type: "Data Files",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Market Data", "Analytics", "Performance"],
        question: "What market data files are available for analysis?",
        answer: "Our market data files include historical price data, volume analysis, sector performance metrics, and economic indicators. These files are updated daily and provide comprehensive market intelligence for investment decision-making.",
        updatedAt: "2025-01-15T00:00:00Z",
        updatedBy: "Data Team"
      },
      {
        id: "8-2",
        type: "Data Files",
        strategy: "Firm-Wide (Not Strategy-Specific)",
        tags: ["Client Data", "Portfolio", "Reporting"],
        question: "What client portfolio data files are maintained?",
        answer: "We maintain comprehensive client portfolio data files including holdings, transactions, performance metrics, and risk assessments. All data is encrypted and stored securely in compliance with regulatory requirements.",
        updatedAt: "2025-01-14T00:00:00Z",
        updatedBy: "Portfolio Team"
      }
    ]
  }
];
