import { ContentItem } from "@/types/vault";

// Generate realistic demo data matching the screenshots
export const MOCK_CONTENT_ITEMS: ContentItem[] = [
  {
    id: "1",
    title: "AI_Policy_Document_April_2025",
    type: "Policy",
    strategy: "Firm-Wide (Not Strategy-Specific)",
    tags: ["AI", "Policy", "Compliance"],
    totalItems: 22,
    content: {
      question: "What specific pre-approval requirements must Granite Peak employees adhere to when using AI Systems involving proprietary information, and what roles do the Deputy CCO and Director of Operations play in the due diligence process to prevent unauthorized sharing of confidential information?",
      answer: "Granite Peak maintains an Acceptable Use of Artificial Intelligence (\"AI\") Systems Policy (below). The use of artificial intelligence and natural language processing programs and related software i.e., ChatGPT, CoPilot, Bard, and others by the Firm and its employees must comply with all applicable laws, regulations, and the ethical principles outlined in this Compliance Manual and the Firm's Code of Ethics, including those related to the protection of sensitive firm and client information outlined in the Firm's Cybersecurity and Information Security Policy. Before formally implementing any such software, employees must first obtain approval from the Deputy Chief Compliance Officer and Director of Operations. At this time, use of this software is limited to testing only and may not be used for any client facing business purposes i.e., generating investment advice, producing client reports, etc. The Firm and its employees shall comply with the Firm's data protection measures to safeguard sensitive firm and client information when using such software. This includes continued use of firewalls, encryption, access controls, and other measures as outlined in the Firm's Cybersecurity and Information Security Policy and as deemed necessary by Compliance. At this time, inputting client data into any unsupported AI system is prohibited. Supported AI systems include Firm approved vendors who have their own proprietary AI system within their platform). Should the parameters surround inputting client data change, the Firm shall provide appropriate disclosures to clients regarding the use of such software in formulating investment advice, reports, etc. to the extent deemed necessary. The Firm shall implement appropriate risk management measures to mitigate potential risks associated with the use of AI systems and related software, including disaster recovery planning and regular system backups. The use of such software will be subject to ongoing supervision and monitoring by Compliance. This includes conducting regular reviews of output generated by the software, as well as monitoring data feeds and other inputs. Employees will receive appropriate training on the proper use of these tools, including data protection, model validation, and ethical considerations."
    },
    updatedAt: "2025-08-27T10:00:00Z",
    updatedBy: "Brian"
  },
  {
    id: "2", 
    title: "CalPERS Pension Fund Global Fixed Income Strategy Management",
    type: "Questionnaire",
    strategy: "Fixed Income",
    tags: ["CalPERS", "Fixed Income", "Pension"],
    totalItems: 3,
    content: {
      question: "How does your firm approach duration management in volatile interest rate environments?",
      answer: "Our duration management strategy employs a dynamic hedging approach that adjusts based on market volatility indicators and Fed policy expectations..."
    },
    updatedAt: "2025-08-25T14:30:00Z",
    updatedBy: "Mary"
  },
  {
    id: "3",
    title: "Comprehensive Request for Proposal (RFP)",
    type: "Questionnaire", 
    strategy: "Firm-Wide (Not Strategy-Specific)",
    tags: ["RFP", "General"],
    totalItems: 1,
    content: {
      question: "What is your fee structure for institutional mandates?",
      answer: "Our institutional fee structure is tiered based on assets under management and strategy complexity..."
    },
    updatedAt: "2025-08-24T09:15:00Z",
    updatedBy: "Alex"
  },
  {
    id: "4",
    title: "ESG Triple-Double Fund: Request for Proposal (RFP)", 
    type: "Questionnaire",
    strategy: "ESG Investments",
    tags: ["ESG", "RFP", "Sustainability"],
    totalItems: 20,
    content: {
      question: "How do you integrate ESG factors into your investment process?",
      answer: "ESG integration is fundamental to our investment philosophy. We employ a comprehensive framework that evaluates environmental, social, and governance factors alongside traditional financial metrics..."
    },
    updatedAt: "2025-08-23T16:45:00Z", 
    updatedBy: "Sarah"
  },
  {
    id: "5",
    title: "Global Emerging Markets Dunk Fund: Request for Proposal (RFP)",
    type: "Questionnaire",
    strategy: "Global Emerging Markets", 
    tags: ["Emerging Markets", "RFP"],
    totalItems: 16,
    content: {
      question: "What is your approach to managing currency risk in emerging markets?",
      answer: "Our emerging markets currency risk management employs a multi-layered approach including natural hedging, forward contracts, and options strategies..."
    },
    updatedAt: "2025-08-22T11:20:00Z",
    updatedBy: "David"
  },
  {
    id: "6",
    title: "Investment Approach",
    type: "Commentary",
    strategy: "Large Cap Growth",
    tags: ["Investment Philosophy", "Growth"],
    totalItems: 50,
    content: {
      body: "Our investment approach focuses on identifying companies with sustainable competitive advantages and consistent growth trajectories..."
    },
    updatedAt: "2025-08-21T08:30:00Z",
    updatedBy: "Michael"
  },
  {
    id: "7",
    title: "Investment Management Proposal", 
    type: "Questionnaire",
    strategy: "Firm-Wide (Not Strategy-Specific)",
    tags: ["Investment Management", "Proposal"],
    totalItems: 4,
    content: {
      question: "What are your risk management procedures?",
      answer: "Our comprehensive risk management framework includes position sizing limits, correlation analysis, stress testing, and daily monitoring protocols..."
    },
    updatedAt: "2025-08-20T13:45:00Z",
    updatedBy: "John"
  },
  {
    id: "8",
    title: "Large-Cap All-Star Fund: Request for Proposal (RFP)",
    type: "Questionnaire", 
    strategy: "Large Cap Equity",
    tags: ["Large Cap", "RFP", "All-Star"],
    totalItems: 26,
    content: {
      question: "What is your investment philosophy for large-cap equity strategies?",
      answer: "Our large-cap equity philosophy centers on fundamental analysis and long-term value creation through careful security selection..."
    },
    updatedAt: "2025-08-19T10:00:00Z",
    updatedBy: "Lisa"
  }
];